server:
  port: 8081

spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:phonenumbersdb
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
      show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: 'true'
    path: /swagger-ui.html